name: Deploy binaries
on:
  push:
    branches:
      - test
jobs:
  Run-Tests:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          lfs: true
          submodules: true
      - name: Get submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: |
          brew install cmake ninja glfw libomp eigen boost s3cmd
      - name: Deploy project
        run: |
          ./deploy.sh

